In [2]:
import torch 

In [3]:
tensor1 = torch.Tensor([[1,2,3],
                       [5,6,7]])
tensor1

tensor([[1., 2., 3.],
        [5., 6., 7.]])

In [4]:
tensor2 = torch.Tensor([[9,10,3],
                       [12,13,7]])
tensor2

tensor([[ 9., 10.,  3.],
        [12., 13.,  7.]])

In [5]:
#When the value for the below function is true , pytorch will track computations for a tensor in the forward phas and will calculate gradients for this tensor in the backward phase
tensor1.requires_grad


False

In [6]:
tensor2.requires_grad

False

To Enable tracking history for a particular tensor we cal call the requires_grad_() function

In [7]:
tensor1.requires_grad_()


tensor([[1., 2., 3.],
        [5., 6., 7.]], requires_grad=True)

In [8]:
tensor2.requires_grad

False

In [9]:
tensor1.requires_grad


True

In [10]:
tensor2.requires_grad_()

tensor([[ 9., 10.,  3.],
        [12., 13.,  7.]], requires_grad=True)

No gradients are available yet- this is part of a computation graph but no forward or backward passes have been made

In [11]:
print(tensor1.grad)

None


The computation graph in pytorch is made up of tensors and function

Tensors are nodes in the graph and functions are the transformations performed along edges 

In [12]:
print(tensor1.grad_fn)

None


In [13]:
output_tensor = tensor1 * tensor2

In [14]:
output_tensor.requires_grad

True

In [15]:
print(output_tensor.grad_fn)

MulBackward is the grad function used here . Neither tensor1 nor tensor2 have grad functions associated with it.

In [16]:
print(tensor1.grad_fn)

None


In [17]:
print(tensor2.grad_fn)

None


In [18]:
output_tensor = (tensor1 * tensor2).mean()
print(output_tensor.grad_fn)

The gradient of the partial derivative will only be calculated when we call the backward() function

In [19]:
output_tensor.backward()

In [20]:
print(tensor1.grad)

tensor([[1.5000, 1.6667, 0.5000],
        [2.0000, 2.1667, 1.1667]])


These gradients here are the partial derivative for the parameters in tensor1 calculated with reference to the output tensor

Since gradients are partial derivatives with respect to every value inside the tensor, the shape of the gradient will be similar to that of the tensor

In [21]:
tensor1.grad.shape , tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [23]:
print(output_tensor.grad)
# No output value since this is the value wth respect to which the gradients where calculated.

None


/home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484806139/work/build/aten/src/ATen/core/TensorBody.h:477.)
  return self._grad


In [25]:
new_tens = tensor1 * 3
print(new_tens.requires_grad)

True


In [26]:
new_tens

tensor([[ 3.,  6.,  9.],
        [15., 18., 21.]], grad_fn=<MulBackward0>)

Stop autograd from tracking history on Tensors with requires_grad=True

In [27]:
with torch.no_grad():
    new_tens = tensor1 * 3
    
    print('new tensor = ',new_tens)
    
    print('requires_grad for tensor = ',tensor1.requires_grad)
    
    print('requires_grad for tensor = ', tensor2.requires_grad)
    
    print('requires_grad for new_tensor = ' , new_tens.requires_grad)

new tensor =  tensor([[ 3.,  6.,  9.],
        [15., 18., 21.]])
requires_grad for tensor =  True
requires_grad for tensor =  True
requires_grad for new_tensor =  False


In [28]:
def calculate(t):
    return t * 2 


In [39]:
@torch.no_grad()
def calculate_with_no_grad(t):
    return t * 2

In [40]:
result_tensor = calculate(tensor1)
result_tensor

tensor([[ 2.,  4.,  6.],
        [10., 12., 14.]], grad_fn=<MulBackward0>)

In [41]:
result_tensor.requires_grad

True

In [42]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)
result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [10., 12., 14.]])

In [43]:
result_tensor_no_grad.requires_grad

False

DECORATORS 

In [47]:
def display_info(func):
    def inner():
        print("Executing",func.__name__,"function")
        func()
        print("Finished Execution")
    return inner
@display_info

def printer():
    print("Hello , World!")
    
printer()

#Adding the @symbol means that we are passing that function as an argument to the decorator function 
#and reassigning the function to the return function
# display_info is the decorator function and we pass the printer function to it and reassign the printer function to the 
#returned inner function 

Executing printer function
Hello , World!
Finished Execution


In [49]:
 with torch.no_grad():
        
        new_tensor_no_grad = tensor1 * 3
        
        print('new_tensor_no_grad = ',new_tensor_no_grad)
        
        with torch.enable_grad():
            new_tensor_no_grad = tensor1 * 3
            
            print('new_tensor_no_grad= ',new_tensor_no_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [15., 18., 21.]])
new_tensor_no_grad=  tensor([[ 3.,  6.,  9.],
        [15., 18., 21.]], grad_fn=<MulBackward0>)


In [52]:
tensor_one = torch.tensor([[1.0,2.0],
                          [3.0,4.0]],requires_grad=True)
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [54]:
tensor_two = torch.tensor([[5.0,6.0],
                          [7.0,8.0]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [55]:
tensor_two.requires_grad

False

In [56]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [57]:
final_tensor = (tensor_one + tensor_two).mean()
final_tensor


tensor(9., grad_fn=<MeanBackward0>)

In [58]:
final_tensor.requires_grad

True

In [59]:
print(tensor_one.grad)

None


In [60]:
print(tensor_two.grad)

None


#### We have only performed forward pass on our tensors right now, so there will be no gradients associated with the tensors .

#### We will have history tracking enabled when we call final_tensor.backward()

In [62]:
final_tensor.backward()

In [63]:
print(tensor_one.grad)


tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [64]:
print(tensor_two.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


#### If we want a new tensor detached from the current computation graph - will always have requires_grad = False 

In [65]:
detached_tensor = tensor_one.detach()

detached_tensor

tensor([[1., 2.],
        [3., 4.]])

In [66]:
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [67]:
mean_tensor = (tensor_one + detached_tensor).mean()

mean_tensor.backward()

In [68]:
tensor_one.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [69]:
print(detached_tensor.grad)

None
