### The Variable API in PyTorch Has been deprecated, Variables are no longer needed to work with autograd and to store gradients

In [1]:
import  torch 

from  torch.autograd import Variable

In [3]:
var = Variable(torch.FloatTensor([9]))
var


tensor([9.])

In [4]:
var.requires_grad_()

tensor([9.], requires_grad=True)

In [5]:
var1 = Variable(torch.FloatTensor([3]), requires_grad = True)
var2 = Variable(torch.FloatTensor([7]), requires_grad = True)

In [6]:
var1

tensor([3.], requires_grad=True)

In [7]:
var2

tensor([7.], requires_grad=True)

In [9]:
result_var = var * var1

result_var

tensor([27.], grad_fn=<MulBackward0>)

In [10]:
result_var.requires_grad

True

In [11]:
result_var.backward()

In [12]:
var1.grad

tensor([9.])

In [13]:
var2.grad

In [14]:
var.grad

tensor([3.])