<a href="https://colab.research.google.com/github/rafism1997/Pytorch_Dev/blob/main/ConversionBetweenPytTorchAndNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import torch


In [2]:
tensor = torch.rand(4,3)
tensor

tensor([[0.3969, 0.9246, 0.7501],
        [0.9572, 0.7760, 0.8931],
        [0.4650, 0.9952, 0.2099],
        [0.3044, 0.4373, 0.9906]])

In [3]:
type(tensor)

torch.Tensor

Torch Tensors are simply NumPy arrays with the ability to be executed on GPU's

In [4]:
# We can access the corresponding numpy array for the tensor by simply calling tensor.numpy
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.39694   , 0.9245714 , 0.7501305 ],
       [0.9572164 , 0.7760181 , 0.89307874],
       [0.46504718, 0.9951518 , 0.209876  ],
       [0.30442643, 0.43727803, 0.99060595]], dtype=float32)

In [5]:
type(numpy_from_tensor)

numpy.ndarray

In [6]:
torch.is_tensor(numpy_from_tensor)
# depicting that numpy_from_tensor is a numpy array

False

The NumPy array and PyTorch tensor share the same underlying memory

In [7]:
#for example if we are chamging the numpy array, the same will be reflected in the tensor also

numpy_from_tensor[0,0] = 100.0
numpy_from_tensor

array([[100.        ,   0.9245714 ,   0.7501305 ],
       [  0.9572164 ,   0.7760181 ,   0.89307874],
       [  0.46504718,   0.9951518 ,   0.209876  ],
       [  0.30442643,   0.43727803,   0.99060595]], dtype=float32)

In [8]:
tensor

tensor([[100.0000,   0.9246,   0.7501],
        [  0.9572,   0.7760,   0.8931],
        [  0.4650,   0.9952,   0.2099],
        [  0.3044,   0.4373,   0.9906]])

In [9]:
numpy_arr= np.array([[1.0,2.0,3.0],
                     [20,30,40],
                     [200,300,800]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 20.,  30.,  40.],
       [200., 300., 800.]])

In [10]:
tensor_from_numpy= torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 20.,  30.,  40.],
        [200., 300., 800.]], dtype=torch.float64)

In [11]:
type(tensor_from_numpy)

torch.Tensor

In [12]:
tensor_from_numpy[0]=1 # first raw all ones
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 20.,  30.,  40.],
        [200., 300., 800.]], dtype=torch.float64)

In [13]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 20.,  30.,  40.],
       [200., 300., 800.]])

In [14]:
np_array_one = np.array([4,8])
np_array_one


array([4, 8])

In [15]:
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one
# as_tensor function performs a copy if the data is not already a tensor- here since we 
# are not changing the data type or device the new tensor will just use the same memory

tensor([4, 8])

If the data is already a tensor with the same dtype and device then no copy is performed and a new tensofr is returned with the same computational graph.

In [16]:
np_array_two = np.array([2,2])
np_array_two

array([2, 2])

In [17]:
tensor_from_array_two = torch.tensor(np_array_two)

tensor_from_array_two

tensor([2, 2])

In [18]:
np_array_two[1]=4
np_array_two

array([2, 4])

In [19]:
tensor_from_array_two

tensor([2, 2])