In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In order to initialize the CUDA state for Pytorch , we can call torch.cuda.init(). This is required when interacting with its C API . WHen working in Python the CUDA state is initialized on demand 

In [3]:
torch.cuda.init()

In [4]:
torch.cuda.current_device()

0

In [5]:
# To find the number of cuda enabled devices
torch.cuda.device_count()

1

In [6]:
#To monitor CUDA memory occupied by the tensors that we allocate , we can use the torch.cuda.memory_allocated()
torch.cuda.memory_allocated()

0

In [8]:
#Behind the scenes Pytorch uses a caching memory allocator to speed up memory allocations -this allows fast memory deallocation without device synchronizations
torch.cuda.memory_cached()

/home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/cuda/memory.py:391: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(


0

In [9]:
cuda = torch.device('cuda')
cuda

device(type='cuda')

In [11]:
x = torch.tensor([10,20])
#Since we haven't mentioned where we are implementing the tensor, its created on the cpu
x

tensor([10, 20])

In [13]:
x = torch.tensor([10,20] , device = cuda)
x

tensor([10, 20], device='cuda:0')

In [14]:
y = x.cuda()
y
#returns a copy of this object in cuda memory - if the tensor is already in CUDA memory and on the correct device no copy is performed

tensor([10, 20], device='cuda:0')