<a href="https://colab.research.google.com/github/rafism1997/Pytorch_Dev/blob/main/PytorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 

In [2]:
print(torch.__version__)

1.12.1+cu113


In [5]:
torch.get_default_dtype()
#Only floating points are supported  as the default type

torch.float32

In [6]:
torch.set_default_dtype(torch.int)

TypeError: ignored

In [7]:
torch.set_default_dtype(torch.float64)

In [9]:
torch.get_default_dtype()



torch.float64

Pytorch supports a total of 8 cpu tensor types and 8 gpu tensor type.

In [10]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
torch.is_tensor(tensor_arr)

True

In [16]:
#In order to find out the number of elements in a tensor, we can use the numel function
torch.numel(tensor_arr)

6

In [18]:
tensor_uninintialized = torch.Tensor(3,4)
#if only indicate the shape of the tensor , the resulting tensor object will be uninitialized , pytorch will allocate the memory for the tensor
# but wil not assign any value(random values will be assigned)

In [19]:
tensor_uninintialized


tensor([[5.9608e-316,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [20]:
torch_initialized = torch.rand(2,2)

In [21]:
torch_initialized

tensor([[0.9415, 0.0843],
        [0.2458, 0.0799]])

Creation of a tensor using a specific type 

In [24]:
tensor_int =torch.tensor([5,3]).type(torch.IntTensor)
tensor_int
#If we are creating tensors on a GPU the tensor types will be specified using different classes
#torch.Cuda.IntTensor

tensor([5, 3], dtype=torch.int32)

In [25]:
#torch.ShortTensor will create a tensor of int16 objects(16 bit integers)

tensor_short =torch.ShortTensor([1.0,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [26]:
tensor_float =torch.tensor([1.0,2.0,3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

To fill a tensor with values 

In [27]:
tensor_fill =torch.full((2,6),fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [28]:
tensor_of_ones=torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)