In [27]:
import numpy as np 
import torch 
import torch.nn as nn 

In [28]:
W = torch.randn(6)#Weight

x= torch.tensor([10.0,10.0,10.0,10.0,10.0,10.0])

b=torch.tensor(3)# bias

In [29]:
W

tensor([-1.1712,  1.1991, -0.6785,  1.0100, -1.9383,  0.5521])

In [30]:
y = W*x + b

In [31]:
W

tensor([-1.1712,  1.1991, -0.6785,  1.0100, -1.9383,  0.5521])

In [32]:
y

tensor([ -8.7115,  14.9908,  -3.7848,  13.1002, -16.3830,   8.5206])

In [33]:
W*x

tensor([-11.7115,  11.9908,  -6.7848,  10.1002, -19.3830,   5.5206])

In [34]:
b

tensor(3)

In [35]:
W1 =torch.tensor(6)
W2 =torch.tensor(6)
W3 =torch.tensor(6)

x1 = torch.tensor([2,2,2])
x2 = torch.tensor([3,3,3])
x3 = torch.tensor([4,4,4])

b = torch.tensor(10)

In [36]:
W1,W2,W3

(tensor(6), tensor(6), tensor(6))

In [37]:
intermediate_value = W1 *x1 + W2 * x2
intermediate_value

tensor([30, 30, 30])

In [38]:
final_value = W1 * x1 + W2 * x2 + W3 * x3 +b  
final_value 

tensor([64, 64, 64])

In [39]:
import hiddenlayer as hl 

In [48]:
x_train = np.array([[4.7],[2.4],[7.5],[7.1],[4.3],[7.816],
                    [8.9],[5.2],[8.59],[2.1]],
                   dtype = np.float32)

y_train = np.array([[2.6],[1.6],[3.09],[2.4],[2.4],[3.3567],
                    [2.6],[1.96],[3.53],[1.76]],
                   dtype = np.float32)

In [53]:
X_train =torch.tensor(x_train)

Y_train = torch.tensor(y_train)

X_train.shape

torch.Size([10, 1])

In [54]:
inp = 1

out = 1

hid =100


In [55]:
#Simple sequential network with 2 linear layers.
model1 = torch.nn.Sequential(torch.nn.Linear(inp, hid),
                             torch.nn.Linear(hid, out))

In [59]:
# We pass in 10 data points and there is 1 feature for each data point
hl.build_graph(model1,torch.zeros([10,1]))

TypeError: _jit_pass_onnx_unpack_quantized_weights(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: bool) -> Dict[str, IValue]

Invoked with: graph(%0 : Float(10, 1, strides=[1, 1], requires_grad=0, device=cpu),
      %1 : Float(100, 1, strides=[1, 1], requires_grad=1, device=cpu),
      %2 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %3 : Float(1, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %4 : Float(1, strides=[1], requires_grad=1, device=cpu)):
  %15 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::linear(%0, %1, %2) # /home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py:114:0
  %16 : Float(10, 1, strides=[1, 1], requires_grad=1, device=cpu) = aten::linear(%15, %3, %4) # /home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py:114:0
  return (%16)
, None, False

In [60]:
model2 = torch.nn.Sequential(torch.nn.Linear(inp,hid),
                             torch.nn.Linear(hid,hid),
                             torch.nn.Sigmoid(),
                             torch.nn.Linear(hid,out))

In [61]:
hl.build_graph(model2 , torch.zeros([10,1]))

TypeError: _jit_pass_onnx_unpack_quantized_weights(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: bool) -> Dict[str, IValue]

Invoked with: graph(%0 : Float(10, 1, strides=[1, 1], requires_grad=0, device=cpu),
      %1 : Float(100, 1, strides=[1, 1], requires_grad=1, device=cpu),
      %2 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %3 : Float(100, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %4 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %5 : Float(1, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %6 : Float(1, strides=[1], requires_grad=1, device=cpu)):
  %21 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::linear(%0, %1, %2) # /home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py:114:0
  %22 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::linear(%21, %3, %4) # /home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py:114:0
  %23 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::sigmoid(%22) # /home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/activation.py:290:0
  %24 : Float(10, 1, strides=[1, 1], requires_grad=1, device=cpu) = aten::linear(%23, %5, %6) # /home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py:114:0
  return (%24)
, None, False

In [62]:
from torch.utils.tensorboard import SummaryWriter

# default `log_dir` is "runs" - we'll be more specific here
writer = SummaryWriter('runs/pytorch')

/home/rafistark/anaconda3/envs/pytorch/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [64]:
tensorboard --logdir logs

SyntaxError: invalid syntax (2505290755.py, line 1)