In [10]:
import numpy as np

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [11]:
tf.enable_eager_execution()

In [12]:
tf.executing_eagerly()

True

In [16]:
W =tf.Variable(6,name = 'var_W')

x = tf.constant([10,10], name ='x')
#There is no initial value for a placeholder , the values will be fed in when we execute the
#computation graph

b = tf.Variable(3,name = 'constant_b')

In [17]:
W
#initialization happens rightaway in eager execution , the value is shown close to numpy 

<tf.Variable 'var_W:0' shape=() dtype=int32, numpy=6>

In [18]:
x

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [19]:
b

<tf.Variable 'constant_b:0' shape=() dtype=int32, numpy=3>

In [20]:
y = W * x +b

In [21]:
y
# the computation graph is also executed as we defined it 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([63, 63], dtype=int32)>

In [22]:
# We can print the intermediate values also 
W*x

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([60, 60], dtype=int32)>

In [23]:
# When we are running in eager execution mode in tensorflow , we can also perform NumPy operation on
# our tensors

np_result = np.multiply(W,x)
np_result

array([60, 60], dtype=int32)

In [24]:
W.numpy()

6

In [25]:
y.numpy()

array([63, 63], dtype=int32)

## Debugging Pytorch is just like debugging Python - can use pdb and breakpoints (unlike in tensorflow)